### ISSUE TITLE
Orz跪求文言文SMT的数据集～

### ISSUE THREAD

**Issue by Shuryne** [gumblex/htmllisting-parser#7]
您好，我最近想复现一下文言文翻译的SMT，自己做了一个平行语料数据集，但是感觉质量不太高，以及数量也比较少，看到您之前做过文言文的SMT，所以想求一份您文言文翻译项目中的85w平行语料数据集。实在找不到您的邮箱，只能来这里求一份数据了。若能不吝赐数据，我将不胜感激！！！

**Comment by linonetwo** [comment]
@Shuryne 你最近做得咋样呀，要不要一起来做一个白话转文言的开源项目，我擅长基于模板和规则的 NLP，要是有训练结果的话我们可以做一个纯 JS 的项目，不把数据隐藏在服务器后面

**Comment by linonetwo** [comment]
@gumblex 不开源项目是有什么顾虑吗？这种项目开源了必能将文言文发扬光大
